### PR TITLE
vidxden url resolver

### PR DESCRIPTION
**Pull request by Rogerthis**

### CODE REVIEW

**Comment by t0mm0** [comment]
thanks, i'll take a proper look as soon as i can. one thing i can see off the top of my head is the regexes - can you change them to re.search() (you are only looking for one thing) as i suggested for your last one? 

it looks like you've used a mixture of t0mm0.common.net.Net and urllib2 - can you convert the rest to t0mm0.common.net.Net? 

also i'm not sure if it's something to do with guthub's formatting but the indentation looks a bit weird - can you make sure everything is 4 spaces for indents.

thanks again!

**Comment by Rogerthis** [comment]
t0mm0,
I have done the changes you suggested, but I had a problem with the human verification, using the http_POST command. I have left in my attempts at it in comments. Could you take a look at it.

Thanks,
RogerThis

**Comment by Rogerthis** [comment]
Do you want me to put vidbux into a separate module like you have done with sockshare pointing to putlocker?

**Comment by t0mm0** [comment]
having trouble testing this at the moment - i can't even get anything to play in my browser so i guess the site is having problems :( i'll try again tomorrow.

does vidbux work with this code then? 

i'm thinking it will be better just to alter valid_url() to return True for all sites that work with this code. i think that is what i'll do with sockshare and putlocker too.
thanks,

t0mm0

**Comment by Rogerthis** [comment]
Yeah, I just add it to the valid_url() I had seen you had done that with the es/com of videoweed, and I tried it and it worked.

Having different modules for sockshare and putlocker is an advantage, in that you see which modules have been done. But it's up to you.

**Comment by t0mm0** [comment]
@rogerthis,

just committed this with a bunch of changes - take a look and see if it makes sense.

many thanks for the plugin!

t0mm0

**Pull request merged**
