### PR TITLE
3 plugins and small popup notification code

### PR DESCRIPTION
**Pull request by DragonWin**
3 plugins
2g-hosting, divexstage, nolimitvideo

Added code in common.addon inspired by anarchintoch and daledudes icefilm code (almost similar). It will make a little notification in the lower right hand corner of the screen for x seconds.

### CODE REVIEW

**Comment by t0mm0** [comment]
thanks DragonWin, i'l try and get to this on monday.

**Comment by t0mm0** [comment]
@DragonWin - just had a quick peek - could you make sure indenting is consistent (4 spaces not tabs) and if you could add test links for each of the new plugins in the test addon that would really help with testing.

thanks,

t0mm0

**Comment by DragonWin** [comment]
Which file are you referring to with the indentation ? They all compiled nicely on my computer, but if there is an issue (both cosmetic or functional I'll be happy to fix it) 

I'll add the urls to the test addon.

I'll get it done before monday, but I'm off to bed now ;-)

**Comment by t0mm0** [comment]
looks like the plugins are using tabs. it will work but python is much easier to deal with if you stick with one or the other and mixing within a single file will not work so it is harder to copy and paste stuff if you mix spaces and tabs. read [PEP8](http://www.python.org/dev/peps/pep-0008/) for the gory details. I try and keep everything here as PEP8 compliant as possible so that the code is easier for people to read and work with in the future.

t0mm0

**Comment by DragonWin** [comment]
I think I know what has gone wrong with the tab / spaces, as I wrote the first part in gvim (vim for windows), and Git complained about the linefeed, so I started to mess around with another editor.

I'll look into cleaning it up, after I have tried to setup eclipse for python (using Pydev), and hope it can help me avoid that in the future.

Just read PEP8, so I'll try to follow those rules / guide lines, thanks for the link.

Should I close this pull request and make a new one, when it's cleaned up?

**Comment by t0mm0** [comment]
cool. sorry for being fussy ;) just trying to make everything as clear and maintainable as possible for future devs.

you can either close this and open again later, or just commit your fixes and they will automatically be included in this pull request.

thanks,

t0mm0

**Comment by DragonWin** [comment]
no problem, I'm learning as I go along, and I might as well do it the right way from the start.

I'll just commit my fixes then, and make a post here when done.

Now I just need the eclipse IDE to import external modules (like t0mm0.common etc), then I should be good to go to work on the fixes.

**Comment by DragonWin** [comment]
I have fixed the tab / space issues, and tried to clean up the code according to PEP8, I have also fixed a bug in vidxden where an error log line had a syntax error. I fixed the valid_url for novamov to also recognize embed urls.

I have also added 2 functions that loads and saves data to the addon_data/myaddon/ path.

**Comment by t0mm0** [comment]
thanks DragonWin, just started reading and testing....

**Comment by t0mm0** [comment]
merged with mostly minor edits - thanks DragonWin!

**Pull request merged**
