### PR TITLE
Some new plugins

### PR DESCRIPTION
**Pull request by MusterGit**

### CODE REVIEW

**Comment by t0mm0** [comment]
thanks max!

i think maybe we should pull out your unpacking code (which is much nicer than mine ;)) rather than put it in loads of plugins. i'll try and do that (and merge these plugins) tonight.

thanks,

t0mm0

**Comment by MusterGit** [comment]
Yes, I wanted to ask this but forgot to. There are many hosters using javascript packing. Thanks :)

**Comment by t0mm0** [comment]
i just split out the js unpacking stuff and merged 
- ecostream (though i couldn't find a working stream to test it with)
- uploadc
- videozer
- xvidstage
- stream2k
- skyload

i haven't merged zshare as i couldn't get it to work. i'll compare it to eldorados version and see if that does.

thanks for these!

t0mm0

**Comment by MusterGit** [comment]
zShare definitely worked but I had to give it some minutes to buffer the whole video.

**Comment by MusterGit** [comment]
"\* ecostream (though i couldn't find a working stream to test it with)"

Are you using a nightly build of xbmc? There were some codec problems with previous versions. Ecostream streams are divx encoded.

**Comment by t0mm0** [comment]
yeah it wasn't that the stream wouldn't play, just that i couldn't actually find an ecostream stream to try (the one you added had disappeared by the time i tested) - looks like i managed to miss the 'latest uploads' link on the home page - doh! ;)

**Comment by t0mm0** [comment]
all merged except zshare (still can't get it to work)

21:41:02 T:2833013616   ERROR: Error Type: <type 'exceptions.UnboundLocalError'>
21:41:02 T:2833013616   ERROR: Error Contents: local variable 'stream_url' referenced before assignment
21:41:02 T:2833013616   ERROR: Traceback (most recent call last):
                                              File "/home/paul/.xbmc/addons/plugin.video.t0mm0.test/default.py", line 42, in <module>
                                                stream_url = urlresolver.HostedMediaFile(url=url, host=host, media_id=media_id).resolve()
                                              File "/home/paul/.xbmc/addons/script.module.urlresolver/lib/urlresolver/types.py", line 130, in resolve
                                                return resolver.get_media_url(self._host, self._media_id)
                                              File "/home/paul/.xbmc/addons/script.module.urlresolver/lib/urlresolver/plugins/zshare.py", line 94, in get_media_url
                                                return stream_url
                                            UnboundLocalError: local variable 'stream_url' referenced before assignment
21:41:02 T:9107264   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.t0mm0.test/?url=http%3A%2F%2Fwww.zshare.net%2Fvideo%2F78099511c686d35a%2F&play=True]

going to take a look at eldorados version and see what that does.

thanks for the plugins ;)

**Pull request merged**
